[target.aarch64-linux-android]
linker = "/home/laverna/lai/android-app/ndk-wrap/aarch64-linux-android24-clang"
ar = "/home/laverna/lai/android-app/ndk-wrap/llvm-ar"
rustflags = ["-C", "link-arg=-landroid", "-C", "link-arg=-llog"]

[target.armv7-linux-androideabi]
linker = "/home/laverna/lai/android-app/ndk-wrap/armv7a-linux-androideabi24-clang"
ar = "/home/laverna/lai/android-app/ndk-wrap/llvm-ar"
rustflags = ["-C", "link-arg=-landroid", "-C", "link-arg=-llog"]

[target.i686-linux-android]
linker = "/home/laverna/lai/android-app/ndk-wrap/i686-linux-android24-clang"
ar = "/home/laverna/lai/android-app/ndk-wrap/llvm-ar"
rustflags = ["-C", "link-arg=-landroid", "-C", "link-arg=-llog"]

[target.x86_64-linux-android]
linker = "/home/laverna/bin/lld-link-wrapper.sh"
ar = "/home/laverna/lai/android-app/ndk-wrap/llvm-ar"
rustflags = ["-C", "link-arg=-landroid", "-C", "link-arg=-llog"]
